mongodb/docs-kotlin-sync

source/includes/read/retrieve.kt, source/read.txt, source/read/retrieve.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41134>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/kotlin-sync/DOCSP-41134/read/retrieve/>
=> DOCSP-41134: Retrieve Data

source/includes/read/project.kt, source/read.txt, source/read/project.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41135>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/kotlin-sync/DOCSP-41135-specify-fields/read/project>
=> DOCSP-41135: Specify Fields

source/includes/read/specify-a-query.kt, source/read.txt, source/read/specify-a-query.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41133>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/kotlin-sync/DOCSP-41133-specify-query/read/specify-a-query/>
=> DOCSP-41133: Specify a Query

snooty.toml, source/includes/usage-examples/index-code-examples.kt, source/includes/usage-examples/sample-app.kt, source/index.txt, source/indexes.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41141>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/kotlin-sync/DOCSP-41141-indexes/indexes/>
=> DOCSP-41141: Indexes

snooty.toml, source/includes/indexes/indexes.kt, source/includes/usage-examples/index-code-examples.kt, source/indexes.txt, source/indexes/single-field-index.txt, source/work-with-indexes.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41142>
Staging - 
* <https://preview-mongodbmcmorisi.gatsbyjs.io/kotlin-sync/DOCSP-41142-single-field-indexes/work-with-indexes/>
* <https://preview-mongodbmcmorisi.gatsbyjs.io/kotlin-sync/DOCSP-41142-single-field-indexes/indexes/single-field-index/>
=> DOCSP-41142: Work with Indexes + Single Field Indexes

source/includes/indexes/indexes.kt, source/indexes/compound-index.txt, source/indexes/single-field-index.txt, source/work-with-indexes.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41143>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/kotlin-sync/DOCSP-41143-compound-indexes/indexes/compound-index/>
=> DOCSP-41143: Compound Indexes

source/includes/indexes/indexes.kt, source/indexes/atlas-search-index.txt, source/work-with-indexes.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41144>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/kotlin-sync/DOCSP-41144-atlas-search-index/indexes/atlas-search-index>
=> DOCSP-41144: Atlas Search Indexes

source/includes/read/count.kt, source/read/count.txt
Touching up a page I created earlier in the Kotlin Sync project to meet the standard we're setting with all the other pages.
JIRA - <https://jira.mongodb.org/browse/DOCSP-41455>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/kotlin-sync/DOCSP-41455-standardize-count/read/count/>
=> DOCSP-41455: Standardize Count Documents page

source/data-formats.txt, source/data-formats/bson.txt, source/data-formats/time-series.txt, source/includes/data-formats/time-series.kt
Adapted from the [C++ draft](https://preview-mongodbnorareidy.gatsbyjs.io/cpp-driver/DOCSP-40815-time-series/data-formats/time-series/) and [Kotlin Coroutine](https://www.mongodb.com/docs/drivers/kotlin/coroutine/current/fundamentals/time-series/) versions of this page.
JIRA - <https://jira.mongodb.org/browse/DOCSP-41152>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/kotlin-sync/DOCSP-41152-time-series/data-formats/time-series/>
=> DOCSP-41152: Time Series

source/includes/read/distinct.kt, source/read.txt, source/read/distinct.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41138>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/kotlin-sync/DOCSP-41138-distinct/read/distinct/>
=> DOCSP-41138: Distinct

snooty.toml, source/aggregation.txt, source/includes/aggregation/aggregation.kt, source/index.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41145>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/kotlin-sync/DOCSP-41145-aggregation/aggregation/>
- [] Are all the links working?
=> DOCSP-41145: Aggregation landing page

source/connect.txt, source/connect/connection-targets.txt, source/includes/connect/connection-targets.kt
Adapted from [Pymongo](https://www.mongodb.com/docs/languages/python/pymongo-driver/current/connect/connection-targets/) and [Kotlin Coroutine](https://www.mongodb.com/docs/drivers/kotlin/coroutine/current/fundamentals/connection/connect/).
JIRA - <https://jira.mongodb.org/browse/DOCSP-41122>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/kotlin-sync/DOCSP-41122-connection-targets/connect/connection-targets/>
=> DOCSP-41122: Choose a Connection Target

source/connect.txt, source/get-started/create-a-connection-string.txt, source/includes/connect/compression-tabs.rst, source/includes/connect/disable-host-verification-tabs.rst, source/includes/connect/tls-tabs.rst, source/includes/connect/zlib-level-tabs.rst
JIRA - <https://jira.mongodb.org/browse/DOCSP-42514>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/kotlin-sync/DOCSP-42514-user-pass-plchldr/
=> DOCSP-42514: kotlin user/pass placeholders

snooty.toml, source/builders.txt, source/includes/builders/builders.kt, source/index.txt
Adapted from [the coroutine builders page](https://www.mongodb.com/docs/drivers/kotlin/coroutine/current/fundamentals/builders/), did some trimming and updating.
JIRA - <https://jira.mongodb.org/browse/DOCSP-41161>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/kotlin-sync/DOCSP-41161-builders/builders/>
=> DOCSP-41161: Builders landing page

source/includes/read/change-streams.kt, source/read.txt, source/read/change-streams.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41140>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/kotlin-sync/DOCSP-41140-change-streams/read/change-streams/>
=> DOCSP-41140: Change Streams

source/connect.txt, source/connect/connection-options.txt, source/connect/mongoclient.txt, source/includes/connect/mongoclient.kt, source/includes/connect/mongoclient2.kt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41121>
Staging - <https://preview-mongodblindseymoore.gatsbyjs.io/kotlin-sync/DOCSP-41121-create-mongoclient/connect/mongoclient/>
=> DOCSP-41121 Connect to Mongo Client 

source/index.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41116>
Staging - <https://preview-mongodblindseymoore.gatsbyjs.io/kotlin-sync/DOCSP-41116/whats-new/>
=> DOCSP-41116 What's New

source/connect.txt, source/connect/tls.txt, source/includes/connect/tls.kt
For the most part, completely lifted from the [Coroutine version](https://www.mongodb.com/docs/drivers/kotlin/coroutine/current/fundamentals/connection/tls/).
JIRA - <https://jira.mongodb.org/browse/DOCSP-41508>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/kotlin-sync/DOCSP-41508-TLS/connect/tls/>
=> DOCSP-41508: TLS

source/includes/read/cursors.kt, source/read.txt, source/read/cursors.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41139>
Staging - <https://preview-mongodbmcmorisi.gatsbyjs.io/kotlin-sync/DOCSP-41139-cursor/read/cursors//>
=> DOCSP-41139: Cursors

source/connect.txt, source/connect/connection-options.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41123>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/kotlin-sync/DOCSP-41123-options/connect/connection-options/
=> DOCSP-41123: cxn options

source/data-formats.txt, source/data-formats/codecs.txt, source/data-formats/serialization.txt, source/includes/data-formats/codecs.kt
JIRA - <https://jira.mongodb.org/browse/DOCSP-42813>
Staging - https://preview-mongodbrustagir.gatsbyjs.io/kotlin-sync/DOCSP-42813-codecs/data-formats/codecs/
=> DOCSP-42813: codecs

source/includes/write/transaction.kt, source/write-operations.txt, source/write/transactions.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-41763>
Staging - <https://deploy-preview-47--docs-kotlin-sync.netlify.app/write/transactions/>
=> DOCSP-41763 Add transaction page

source/index.txt, source/indexes/atlas-search-index.txt, source/issues-and-help.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44292>
Staging - https://deploy-preview-51--docs-kotlin-sync.netlify.app/issues-and-help/
=> DOCSP-44292: improve i&h

source/connect.txt, source/data-formats.txt, source/get-started.txt, source/index.txt, source/indexes.txt, source/indexes/single-field-index.txt, source/read.txt, source/work-with-indexes.txt, source/write-operations.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-44904>
Staging - <https://deploy-preview-55--docs-kotlin-sync.netlify.app/>
=> DOCSP-44904 Shorten TOC Labels

source/api.txt, source/builders.txt, source/builders/builders-data-classes.txt, source/data-formats.txt, source/data-formats/data-format-data-class.txt, source/includes/builders/builders-data-class.kt, source/includes/data-formats/builders-dataclass.rst, source/includes/data-formats/data-class.kt, source/index.txt, source/whats-new.txt
CONTENT FROM https://github.com/mongodb/docs-kotlin/pull/186
JIRA - <https://jira.mongodb.org/browse/DOCSP-36218>
- [main page](https://deploy-preview-63--docs-kotlin-sync.netlify.app/builders/builders-data-classes/)
- [whats new](https://deploy-preview-63--docs-kotlin-sync.netlify.app/whats-new/#std-label-kotlin-sync-version-5.3)
- [data class](https://deploy-preview-63--docs-kotlin-sync.netlify.app/data-formats/data-format-data-class/)
=> DOCSP-36218: filters with dataclass properties

source/includes/run-command.kt, source/index.txt, source/run-command.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46791>
Staging - <https://deploy-preview-61--docs-kotlin-sync.netlify.app/run-command/>
=> [Kotlin Sync] Run a Command

source/includes/monitoring_JMX.kt, source/includes/monitoring_counter.kt, source/includes/monitoring_librarian.kt, source/includes/monitoring_writable.kt, source/index.txt, source/monitoring.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46789>
<li><a href=https://deploy-preview-65--docs-kotlin-sync.netlify.app/monitoring>monitoring</a></li><li><a href=https://deploy-preview-65--docs-kotlin-sync.netlify.app/index>index</a></li>
=> [Kotlin Sync] Monitoring > Cluster Monitoring

config/redirects
JIRA - <https://jira.mongodb.org/browse/DOCSP-47962>
Extension to the ticket: after fixing the base I realized the base had duplicate /docs, removed one /docs to make sure the URL works
=> DOCSP-47962 realized duplicate /docs in url redirect

source/includes/write/client-bulk-write.kt, source/whats-new.txt, source/write/bulk-write.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46772>
<li><a href=https://deploy-preview-85--docs-kotlin-sync.netlify.app/whats-new>whats-new</a></li><li><a href=https://deploy-preview-85--docs-kotlin-sync.netlify.app/write/bulk-write>write/bulk-write</a></li>
=> DOCSP-46772: sort option for client bw - updateone & replaceone

source/includes/security/enterprise-auth.kt, source/security/enterprise-auth.txt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-47923>
<li><a href=https://deploy-preview-86--docs-kotlin-sync.netlify.app/security/enterprise-auth>security/enterprise-auth</a></li><li><a href=https://deploy-preview-86--docs-kotlin-sync.netlify.app/whats-new>whats-new</a></li>
=> DOCSP-47923: kubernetes oidc

config/redirects, snooty.toml, source/monitoring.txt, source/whats-new.txt, source/write/transactions.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48677>
<li><a href=https://deploy-preview-88--docs-kotlin-sync.netlify.app/monitoring>monitoring</a></li><li><a href=https://deploy-preview-88--docs-kotlin-sync.netlify.app/whats-new>whats-new</a></li><li><a href=https://deploy-preview-88--docs-kotlin-sync.netlify.app/write/transactions>write/transactions</a></li>
=> DOCSP-48677: v5.4 release

source/data-formats/serialization.txt, source/includes/data-formats/serialization.kt, source/whats-new.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-46215>
<li><a href=https://deploy-preview-90--docs-kotlin-sync.netlify.app/data-formats/serialization>data-formats/serialization</a></li><li><a href=https://deploy-preview-90--docs-kotlin-sync.netlify.app/whats-new>whats-new</a></li>
=> [Kotlin Sync] Support naming strategy for bson-kotlinx

source/connect/connection-targets.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-48758>
<li><a href=https://deploy-preview-92--docs-kotlin-sync.netlify.app/connect/connection-targets>connect/connection-targets</a></li>
=> DOCSP-48758: docker note

config/redirects, source/security/authentication.txt, source/whats-new.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-49751
<li><a href=https://deploy-preview-96--docs-kotlin-sync.netlify.app/security/authentication>security/authentication</a></li><li><a href=https://deploy-preview-96--docs-kotlin-sync.netlify.app/whats-new>whats-new</a></li>
=> DOCSP-49751: v5.5 release

source/security/authentication.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-50021
<li><a href=https://deploy-preview-97--docs-kotlin-sync.netlify.app/security/authentication>security/authentication</a></li>
=> DOCSP-50021: Remove eol server mentions

source/builders/builders-data-classes.txt, source/data-formats/bson.txt, source/data-formats/serialization.txt, source/includes/data-formats/bson-gradle-versioned.rst, source/includes/data-formats/bson-maven-versioned.rst, source/includes/data-formats/serialization-gradle-versioned.rst, source/includes/data-formats/serialization-maven-versioned.rst, source/includes/security/crypt-gradle-versioned.rst, source/includes/security/crypt-maven-versioned.rst, source/index.txt, source/security/authentication.txt, source/security/encrypt-fields.txt
JIRA - <https://jira.mongodb.org/browse/DOCSP-49013>
<li><a href=https://deploy-preview-99--docs-kotlin-sync.netlify.app/builders/builders-data-classes>builders/builders-data-classes</a></li><li><a href=https://deploy-preview-99--docs-kotlin-sync.netlify.app/data-formats/bson>data-formats/bson</a></li><li><a href=https://deploy-preview-99--docs-kotlin-sync.netlify.app/data-formats/serialization>data-formats/serialization</a></li><li><a href=https://deploy-preview-99--docs-kotlin-sync.netlify.app/index>index</a></li><li><a href=https://deploy-preview-99--docs-kotlin-sync.netlify.app/security/authentication>security/authentication</a></li><li><a …
=> DOCSP-49013 BOM Tip for Kotlin Sync
